# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    http_method_override: false
    request:
        formats:
            json: 'application/json'
    #esi: true
    #fragments: true
    php_errors:
        log: true
        
    http_client:
        scoped_clients:
            off.fr.client:
                base_uri: 'https://fr.openfoodfacts.org'
                headers:
                    Accept: 'application/json'
                    User-Agent: 'symfony-ddd-tdd-api - Server - Version 1.0'
when@test:
    framework:
        test: true
