nelmio_api_doc:
    documentation:
        info:
            title: Tekyn test
            description: An API to search and manage food products.
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
