home_redirect:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        route: 'app.swagger_ui'
        permanent: true

api_login_check:
    path: /api/login
